### ISSUE TITLE
Time/Test servlet not being served

### ISSUE THREAD

**Issue by toaler** [jetty-project/embedded-servlet-3.1#3]
I ran "mvn clean install exec:exec", however when jetty is up and running, it's not serving TimeServlet.java/TestServlet.java.  I have the log which i'll attach.  The version of Java I used was:

java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

**Comment by toaler** [comment]
Here's the output from exec:exec.  Doesn't seem the TimeServlet/TestServlet are being recognized.

[INFO] Scanning for projects...
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building embedded-servlet-3.1 1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2:exec (default-cli) @ embedded-servlet-3.1 ---
2015-08-30 23:00:35.814:INFO::main: Logging initialized @119ms
Using BaseResource: file:///Users/btoal/git/embedded-servlet-3.1/target/embedded-servlet-3.1-1-SNAPSHOT/WEB-INF/
2015-08-30 23:00:35.900:INFO:oejs.Server:main: jetty-9.2.10.v20150310
2015-08-30 23:00:36.001:INFO:oejw.StandardDescriptorProcessor:main: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
2015-08-30 23:00:36.022:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@56cbfb61{/,file:/Users/btoal/git/embedded-servlet-3.1/target/embedded-servlet-3.1-1-SNAPSHOT/WEB-INF/,AVAILABLE}
2015-08-30 23:00:36.040:INFO:oejs.ServerConnector:main: Started ServerConnector@5afa04c{HTTP/1.1}{0.0.0.0:8080}
2015-08-30 23:00:36.040:INFO:oejs.Server:main: Started @348ms
org.eclipse.jetty.server.Server@3cb5cdba - STARTED
 += qtp1915910607{STARTED,8<=8<=200,i=3,q=0} - STARTED
 |   +- 11 qtp1915910607-11-selector-ServerConnectorManager@10e5ef01/0 BLOCKED @ java.lang.ClassLoader.findNative(ClassLoader.java:1956)
 |   +- 12 qtp1915910607-12-selector-ServerConnectorManager@10e5ef01/3 RUNNABLE @ java.lang.ClassLoader$NativeLibrary.find(Native Method)
 |   +- 13 qtp1915910607-13-acceptor-0@4d1f3c1e-ServerConnector@5afa04c{HTTP/1.1}{0.0.0.0:8080} BLOCKED @ java.lang.ClassLoader.findNative(ClassLoader.java:1956)
 |   +- 14 qtp1915910607-14-selector-ServerConnectorManager@10e5ef01/1 RUNNABLE @ java.lang.ClassLoader$NativeLibrary.find(Native Method)
 |   +- 15 qtp1915910607-15 TIMED_WAITING @ sun.misc.Unsafe.park(Native Method) IDLE
 |   +- 16 qtp1915910607-16 TIMED_WAITING @ sun.misc.Unsafe.park(Native Method) IDLE
 |   +- 17 qtp1915910607-17 TIMED_WAITING @ sun.misc.Unsafe.park(Native Method) IDLE
 |   +- 18 qtp1915910607-18-selector-ServerConnectorManager@10e5ef01/2 BLOCKED @ java.lang.ClassLoader.findNative(ClassLoader.java:1956)
 += ServerConnector@5afa04c{HTTP/1.1}{0.0.0.0:8080} - STARTED
 |   +~ org.eclipse.jetty.server.Server@3cb5cdba - STARTED
 |   +~ qtp1915910607{STARTED,8<=8<=200,i=3,q=0} - STARTED
 |   += org.eclipse.jetty.util.thread.ScheduledExecutorScheduler@6433a2 - STARTED
 |   +- org.eclipse.jetty.io.ArrayByteBufferPool@7921b0a2
 |   += HttpConnectionFactory@174d20a{HTTP/1.1} - STARTED
 |   |   +- HttpConfiguration@66d2e7d9{32768/8192,8192/8192,https://:0,[]}
 |   += org.eclipse.jetty.server.ServerConnector$ServerConnectorManager@10e5ef01 - STARTED
 |   |   +- org.eclipse.jetty.io.SelectorManager$ManagedSelector@23ceabc1 keys=0 selected=0 id=0
 |   |   |   +- org.eclipse.jetty.io.SelectorManager$ManagedSelector.select(SelectorManager.java:596)
 |   |   |   +- sun.nio.ch.KQueueSelectorImpl@647826f6 keys=0
 |   |   +- org.eclipse.jetty.io.SelectorManager$ManagedSelector@6cc4c815 keys=0 selected=0 id=1
 |   |   |   +- org.eclipse.jetty.io.SelectorManager$ManagedSelector.select(SelectorManager.java:596)
 |   |   |   +- sun.nio.ch.KQueueSelectorImpl@6006586a keys=0
 |   |   +- org.eclipse.jetty.io.SelectorManager$ManagedSelector@3a82f6ef keys=0 selected=0 id=2
 |   |   |   +- org.eclipse.jetty.io.SelectorManager$ManagedSelector.select(SelectorManager.java:596)
 |   |   |   +- sun.nio.ch.KQueueSelectorImpl@7276a84f keys=0
 |   |   +- org.eclipse.jetty.io.SelectorManager$ManagedSelector@100fc185 keys=0 selected=0 id=3
 |   |       +- org.eclipse.jetty.io.SelectorManager$ManagedSelector.select(SelectorManager.java:596)
 |   |       +- sun.nio.ch.KQueueSelectorImpl@61f01735 keys=0
 |   +- sun.nio.ch.ServerSocketChannelImpl[/0:0:0:0:0:0:0:0:8080]
 |   +- qtp1915910607-13-acceptor-0@4d1f3c1e-ServerConnector@5afa04c{HTTP/1.1}{0.0.0.0:8080}
 += o.e.j.w.WebAppContext@56cbfb61{/,file:/Users/btoal/git/embedded-servlet-3.1/target/embedded-servlet-3.1-1-SNAPSHOT/WEB-INF/,AVAILABLE} - STARTED
 |   += org.eclipse.jetty.server.session.SessionHandler@643b1d11 - STARTED
 |   |   += org.eclipse.jetty.server.session.HashSessionManager@13969fbe - STARTED
 |   |   |   += org.eclipse.jetty.util.thread.ScheduledExecutorScheduler@2ef5e5e3 - STARTED
 |   |   |   |   +- sun.misc.Unsafe.park(Native Method)
 |   |   |   |   +- java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
 |   |   |   |   +- java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
 |   |   |   |   +- java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
 |   |   |   |   +- java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
 |   |   |   |   +- java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
 |   |   |   |   +- java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
 |   |   |   |   +- java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 |   |   |   |   +- java.lang.Thread.run(Thread.java:745)
 |   |   |   +~ org.eclipse.jetty.server.session.HashSessionIdManager@36d4b5c - STARTED
 |   |   |   +~ org.eclipse.jetty.security.SecurityHandler$1@6d00a15d
 |   |   += org.eclipse.jetty.security.ConstraintSecurityHandler@51efea79 - STARTED
 |   |       +- org.eclipse.jetty.security.DefaultAuthenticatorFactory@5034c75a
 |   |       += org.eclipse.jetty.servlet.ServletHandler@396a51ab - STARTED
 |   |       |   += org.eclipse.jetty.servlet.ListenerHolder@51081592 - STARTED
 |   |       |   += org.eclipse.jetty.servlet.ListenerHolder@7f9a81e8 - STARTED
 |   |       |   += default@5c13d641==org.eclipse.jetty.servlet.DefaultServlet,0,true - STARTED
 |   |       |   |   +- aliases=false
 |   |       |   |   +- dirAllowed=true
 |   |       |   |   +- maxCacheSize=256000000
 |   |       |   |   +- maxCachedFileSize=200000000
 |   |       |   |   +- welcomeServlets=false
 |   |       |   |   +- useFileMappedBuffer=true
 |   |       |   |   +- gzip=false
 |   |       |   |   +- acceptRanges=true
 |   |       |   |   +- etags=false
 |   |       |   |   +- maxCachedFiles=2048
 |   |       |   |   +- redirectWelcome=false
 |   |       |   += jsp@19c47==org.eclipse.jetty.servlet.NoJspServlet,0,true - STARTED
 |   |       |   |   +- fork=false
 |   |       |   |   +- compilerSourceVM=1.7
 |   |       |   |   +- logVerbosityLevel=DEBUG
 |   |       |   |   +- compilerTargetVM=1.7
 |   |       |   |   +- xpoweredBy=false
 |   |       |   +- [/]=>default
 |   |       |   +- [*.jsp, *.jspf, *.jspx, *.xsp, *.JSP, *.JSPF, *.JSPX, *.XSP]=>jsp
 |   |       |
 |   |       +> null
 |   |       +> null
 |   |       +> null
 |   |       +> []
 |   |       +> /={TRACE={RoleInfo,F,C[],None}, TRACE.omission={RoleInfo[],None}}
 |   += org.eclipse.jetty.servlet.ErrorPageErrorHandler@9629756 - STARTED
 |   |
 |   +> WebAppClassLoader=668849042@27ddd392
 |   |   +- sun.misc.Launcher$AppClassLoader@28d93b30
 |   |       +- file:/Users/btoal/git/embedded-servlet-3.1/target/test-classes
 |   |       +- file:/Users/btoal/git/embedded-servlet-3.1/target/classes/
 |   |       +- file:/Users/btoal/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar
 |   |       +- file:/Users/btoal/.m2/repository/org/eclipse/jetty/jetty-webapp/9.2.10.v20150310/jetty-webapp-9.2.10.v20150310.jar
 |   |       +- file:/Users/btoal/.m2/repository/org/eclipse/jetty/jetty-xml/9.2.10.v20150310/jetty-xml-9.2.10.v20150310.jar
 |   |       +- file:/Users/btoal/.m2/repository/org/eclipse/jetty/jetty-util/9.2.10.v20150310/jetty-util-9.2.10.v20150310.jar
 |   |       +- file:/Users/btoal/.m2/repository/org/eclipse/jetty/jetty-servlet/9.2.10.v20150310/jetty-servlet-9.2.10.v20150310.jar
 |   |       +- file:/Users/btoal/.m2/repository/org/eclipse/jetty/jetty-security/9.2.10.v20150310/jetty-security-9.2.10.v20150310.jar
 |   |       +- file:/Users/btoal/.m2/repository/org/eclipse/jetty/jetty-server/9.2.10.v20150310/jetty-server-9.2.10.v20150310.jar
 |   |       +- file:/Users/btoal/.m2/repository/org/eclipse/jetty/jetty-http/9.2.10.v20150310/jetty-http-9.2.10.v20150310.jar
 |   |       +- file:/Users/btoal/.m2/repository/org/eclipse/jetty/jetty-io/9.2.10.v20150310/jetty-io-9.2.10.v20150310.jar
 |   |       +- file:/Users/btoal/.m2/repository/org/eclipse/jetty/jetty-annotations/9.2.10.v20150310/jetty-annotations-9.2.10.v20150310.jar
 |   |       +- file:/Users/btoal/.m2/repository/org/eclipse/jetty/jetty-plus/9.2.10.v20150310/jetty-plus-9.2.10.v20150310.jar
 |   |       +- file:/Users/btoal/.m2/repository/org/eclipse/jetty/jetty-jndi/9.2.10.v20150310/jetty-jndi-9.2.10.v20150310.jar
 |   |       +- file:/Users/btoal/.m2/repository/javax/annotation/javax.annotation-api/1.2/javax.annotation-api-1.2.jar
 |   |       +- file:/Users/btoal/.m2/repository/org/ow2/asm/asm/5.0.1/asm-5.0.1.jar
 |   |       +- file:/Users/btoal/.m2/repository/org/ow2/asm/asm-commons/5.0.1/asm-commons-5.0.1.jar
 |   |       +- file:/Users/btoal/.m2/repository/org/ow2/asm/asm-tree/5.0.1/asm-tree-5.0.1.jar
 |   |       +- sun.misc.Launcher$ExtClassLoader@62ee68d8
 |   +> javax.servlet.context.tempdir=/private/var/folders/p1/1jy6qcz952x_gs21xk8gjl90r467rt/T/jetty-0.0.0.0-8080-WEB-INF-_-any-6734924320149905829.dir
 |   +> org.eclipse.jetty.lifecyleCallbackCollection=org.eclipse.jetty.plus.annotation.LifeCycleCallbackCollection@735b5592
 |   +> org.eclipse.jetty.server.Executor=qtp1915910607{STARTED,8<=8<=200,i=3,q=0}
 |   +> org.eclipse.jetty.injectionCollection=org.eclipse.jetty.plus.annotation.InjectionCollection@58651fd0
 |   +> org.eclipse.jetty.runAsCollection=org.eclipse.jetty.plus.annotation.RunAsCollection@4520ebad
 +- {}
 +- {}
 +- {}
 += org.eclipse.jetty.server.session.HashSessionIdManager@36d4b5c - STARTED
 |
 +> sun.misc.Launcher$AppClassLoader@28d93b30
     +- file:/Users/btoal/git/embedded-servlet-3.1/target/test-classes
     +- file:/Users/btoal/git/embedded-servlet-3.1/target/classes/
     +- file:/Users/btoal/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar
     +- file:/Users/btoal/.m2/repository/org/eclipse/jetty/jetty-webapp/9.2.10.v20150310/jetty-webapp-9.2.10.v20150310.jar
     +- file:/Users/btoal/.m2/repository/org/eclipse/jetty/jetty-xml/9.2.10.v20150310/jetty-xml-9.2.10.v20150310.jar
     +- file:/Users/btoal/.m2/repository/org/eclipse/jetty/jetty-util/9.2.10.v20150310/jetty-util-9.2.10.v20150310.jar
     +- file:/Users/btoal/.m2/repository/org/eclipse/jetty/jetty-servlet/9.2.10.v20150310/jetty-servlet-9.2.10.v20150310.jar
     +- file:/Users/btoal/.m2/repository/org/eclipse/jetty/jetty-security/9.2.10.v20150310/jetty-security-9.2.10.v20150310.jar
     +- file:/Users/btoal/.m2/repository/org/eclipse/jetty/jetty-server/9.2.10.v20150310/jetty-server-9.2.10.v20150310.jar
     +- file:/Users/btoal/.m2/repository/org/eclipse/jetty/jetty-http/9.2.10.v20150310/jetty-http-9.2.10.v20150310.jar
     +- file:/Users/btoal/.m2/repository/org/eclipse/jetty/jetty-io/9.2.10.v20150310/jetty-io-9.2.10.v20150310.jar
     +- file:/Users/btoal/.m2/repository/org/eclipse/jetty/jetty-annotations/9.2.10.v20150310/jetty-annotations-9.2.10.v20150310.jar
     +- file:/Users/btoal/.m2/repository/org/eclipse/jetty/jetty-plus/9.2.10.v20150310/jetty-plus-9.2.10.v20150310.jar
     +- file:/Users/btoal/.m2/repository/org/eclipse/jetty/jetty-jndi/9.2.10.v20150310/jetty-jndi-9.2.10.v20150310.jar
     +- file:/Users/btoal/.m2/repository/javax/annotation/javax.annotation-api/1.2/javax.annotation-api-1.2.jar
     +- file:/Users/btoal/.m2/repository/org/ow2/asm/asm/5.0.1/asm-5.0.1.jar
     +- file:/Users/btoal/.m2/repository/org/ow2/asm/asm-commons/5.0.1/asm-commons-5.0.1.jar
     +- file:/Users/btoal/.m2/repository/org/ow2/asm/asm-tree/5.0.1/asm-tree-5.0.1.jar
     +- sun.misc.Launcher$ExtClassLoader@62ee68d8

**Comment by joakime** [comment]
`+= o.e.j.w.WebAppContext@56cbfb6{/,file:/Users/btoal/git/embedded-servlet-3.1/target/embedded-servlet-3.1-1-SNAPSHOT/WEB-INF/,AVAILABLE} - STARTED`

The startup used the wrong WAR/BaseResource reference.
That `file:/` reference should use either the WAR file (that you just built) or the directory above "WEB-INF"

I'll fix that.

**Comment by joakime** [comment]
Fixed in [master]

**Comment by toaler** [comment]
If I deploy this embedme app and wanted to start the server from the
commands line, what needs to be on the classpath?  I'm assuming only the
war?
