### ISSUE TITLE
getting embedded driver to honor WebServlet annotation in fatjar

### ISSUE THREAD

**Issue by toaler** [jetty-project/embedded-servlet-3.1#5]
I'm running into a issue when trying to use WebServlet annotations.  I have the following class:

package wts.servlet;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

@SuppressWarnings("serial")
@WebServlet(urlPatterns =
{ "/test" })
public class Test extends HttpServlet
{
    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException
    {
        request.getRequestDispatcher("/WEB-INF/html/index.html").forward(request,response);
    }
}

Then i create a fatjar using maven shade where Test.class lives in the top level dir:

$ tar tvf target/wts-1-SNAPSHOT.jar  | grep Test
-rwxrwxrwx  0 0      0           0 Sep  7 16:38 wts/servlet/Test.class

All the dependent jar's have been included in the jar:

jetty-annotation, asm, etc.

My embedded driver looks like:

https://gist.github.com/toaler/59d26841c6e935813ac4

However on startup the servlets with the annotations are not being found.  I suspect it's something to do with how I'm setting the resource base.  Any ideas?

Startup log:

2015-09-07 16:45:01.112:INFO::main: Logging initialized @107ms
path = /Users/btoal/git/web-tech-stack/target/wts-1-SNAPSHOT.jar
2015-09-07 16:45:01.175:INFO:oejs.Server:main: jetty-9.2.z-SNAPSHOT
2015-09-07 16:45:01.265:INFO:oejw.StandardDescriptorProcessor:main: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
2015-09-07 16:45:01.284:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@282ba1e{/,file:/Users/btoal/git/web-tech-stack/target/wts-1-SNAPSHOT.jar,AVAILABLE}
2015-09-07 16:45:01.309:INFO:oejs.ServerConnector:main: Started ServerConnector@6b2fad11{HTTP/1.1}{0.0.0.0:8080}
2015-09-07 16:45:01.310:INFO:oejs.Server:main: Started @307ms
org.eclipse.jetty.server.Server@75412c2f - STARTED
 += qtp1044036744{STARTED,8<=8<=200,i=3,q=0} - STARTED
 |   +- 11 qtp1044036744-11-selector-ServerConnectorManager@5625b026/0 BLOCKED @ java.lang.ClassLoader.findNative(ClassLoader.java:1956)
 |   +- 12 qtp1044036744-12-selector-ServerConnectorManager@5625b026/2 BLOCKED @ java.lang.ClassLoader.findNative(ClassLoader.java:1956)
 |   +- 13 qtp1044036744-13 TIMED_WAITING @ sun.misc.Unsafe.park(Native Method) IDLE
 |   +- 14 qtp1044036744-14-selector-ServerConnectorManager@5625b026/3 RUNNABLE @ sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
 |   +- 15 qtp1044036744-15-selector-ServerConnectorManager@5625b026/1 BLOCKED @ java.lang.ClassLoader.findNative(ClassLoader.java:1956)
 |   +- 16 qtp1044036744-16-acceptor-0@248f4cc7-ServerConnector@6b2fad11{HTTP/1.1}{0.0.0.0:8080} RUNNABLE @ java.lang.ClassLoader$NativeLibrary.find(Native Method)
 |   +- 17 qtp1044036744-17 TIMED_WAITING @ sun.misc.Unsafe.park(Native Method) IDLE
 |   +- 18 qtp1044036744-18 TIMED_WAITING @ sun.misc.Unsafe.park(Native Method) IDLE
 += ServerConnector@6b2fad11{HTTP/1.1}{0.0.0.0:8080} - STARTED
 |   +~ org.eclipse.jetty.server.Server@75412c2f - STARTED
 |   +~ qtp1044036744{STARTED,8<=8<=200,i=3,q=0} - STARTED
 |   += org.eclipse.jetty.util.thread.ScheduledExecutorScheduler@6f539caf - STARTED
 |   +- org.eclipse.jetty.io.ArrayByteBufferPool@2ed94a8b
 |   += HttpConnectionFactory@38082d64{HTTP/1.1} - STARTED
 |   |   +- HttpConfiguration@dfd3711{32768/8192,8192/8192,https://:0,[]}
 |   += org.eclipse.jetty.server.ServerConnector$ServerConnectorManager@5625b026 - STARTED
 |   |   +- org.eclipse.jetty.io.SelectorManager$ManagedSelector@3f2a3a5 keys=0 selected=0 id=0
 |   |   |   +- org.eclipse.jetty.io.SelectorManager$ManagedSelector.select(SelectorManager.java:596)
 |   |   |   +- sun.nio.ch.KQueueSelectorImpl@51b5a70d keys=0
 |   |   +- org.eclipse.jetty.io.SelectorManager$ManagedSelector@614c5515 keys=0 selected=0 id=1
 |   |   |   +- org.eclipse.jetty.io.SelectorManager$ManagedSelector.select(SelectorManager.java:596)
 |   |   |   +- sun.nio.ch.KQueueSelectorImpl@13272486 keys=0
 |   |   +- org.eclipse.jetty.io.SelectorManager$ManagedSelector@77b52d12 keys=0 selected=0 id=2
 |   |   |   +- org.eclipse.jetty.io.SelectorManager$ManagedSelector.select(SelectorManager.java:596)
 |   |   |   +- sun.nio.ch.KQueueSelectorImpl@19dc94b8 keys=0
 |   |   +- org.eclipse.jetty.io.SelectorManager$ManagedSelector@2d554825 keys=0 selected=0 id=3
 |   |       +- org.eclipse.jetty.io.SelectorManager$ManagedSelector.select(SelectorManager.java:596)
 |   |       +- sun.nio.ch.KQueueSelectorImpl@7f0d1f81 keys=0
 |   +- sun.nio.ch.ServerSocketChannelImpl[/0:0:0:0:0:0:0:0:8080]
 |   +- qtp1044036744-16-acceptor-0@248f4cc7-ServerConnector@6b2fad11{HTTP/1.1}{0.0.0.0:8080}
 += o.e.j.w.WebAppContext@282ba1e{/,file:/Users/btoal/git/web-tech-stack/target/wts-1-SNAPSHOT.jar,AVAILABLE} - STARTED
 |   += org.eclipse.jetty.server.session.SessionHandler@68837a77 - STARTED
 |   |   += org.eclipse.jetty.server.session.HashSessionManager@11531931 - STARTED
 |   |   |   += org.eclipse.jetty.util.thread.ScheduledExecutorScheduler@6be46e8f - STARTED
 |   |   |   |   +- sun.misc.Unsafe.park(Native Method)
 |   |   |   |   +- java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
 |   |   |   |   +- java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
 |   |   |   |   +- java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
 |   |   |   |   +- java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
 |   |   |   |   +- java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
 |   |   |   |   +- java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
 |   |   |   |   +- java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 |   |   |   |   +- java.lang.Thread.run(Thread.java:745)
 |   |   |   +~ org.eclipse.jetty.server.session.HashSessionIdManager@3567135c - STARTED
 |   |   |   +~ org.eclipse.jetty.security.SecurityHandler$1@327471b5
 |   |   += org.eclipse.jetty.security.ConstraintSecurityHandler@4157f54e - STARTED
 |   |       +- org.eclipse.jetty.security.DefaultAuthenticatorFactory@90f6bfd
 |   |       += org.eclipse.jetty.servlet.ServletHandler@47f6473 - STARTED
 |   |       |   += org.eclipse.jetty.servlet.ListenerHolder@15975490 - STARTED
 |   |       |   += org.eclipse.jetty.servlet.ListenerHolder@6b143ee9 - STARTED
 |   |       |   += default@5c13d641==org.eclipse.jetty.servlet.DefaultServlet,0,true - STARTED
 |   |       |   |   +- aliases=false
 |   |       |   |   +- dirAllowed=true
 |   |       |   |   +- maxCacheSize=256000000
 |   |       |   |   +- maxCachedFileSize=200000000
 |   |       |   |   +- welcomeServlets=false
 |   |       |   |   +- useFileMappedBuffer=true
 |   |       |   |   +- gzip=false
 |   |       |   |   +- acceptRanges=true
 |   |       |   |   +- etags=false
 |   |       |   |   +- maxCachedFiles=2048
 |   |       |   |   +- redirectWelcome=false
 |   |       |   += jsp@19c47==org.eclipse.jetty.servlet.NoJspServlet,0,true - STARTED
 |   |       |   |   +- fork=false
 |   |       |   |   +- compilerSourceVM=1.7
 |   |       |   |   +- logVerbosityLevel=DEBUG
 |   |       |   |   +- compilerTargetVM=1.7
 |   |       |   |   +- xpoweredBy=false
 |   |       |   +- [/]=>default
 |   |       |   +- [*.jsp, *.jspf, *.jspx, *.xsp, *.JSP, *.JSPF, *.JSPX, *.XSP]=>jsp
 |   |       |
 |   |       +> null
 |   |       +> null
 |   |       +> null
 |   |       +> []
 |   |       +> /={TRACE={RoleInfo,F,C[],None}, TRACE.omission={RoleInfo[],None}}
 |   += org.eclipse.jetty.servlet.ErrorPageErrorHandler@1936f0f5 - STARTED
 |   |
 |   +> WebAppClassLoader=992136656@3b22cdd0
 |   |   +- sun.misc.Launcher$AppClassLoader@45ee12a7
 |   |       +- file:/Users/btoal/git/web-tech-stack/target/wts-1-SNAPSHOT.jar
 |   |       +- sun.misc.Launcher$ExtClassLoader@6615435c
 |   +> javax.servlet.context.tempdir=/private/var/folders/p1/1jy6qcz952x_gs21xk8gjl90r467rt/T/jetty-0.0.0.0-8080-wts-1-SNAPSHOT.jar-_-any-7754798833237785343.dir
 |   +> org.eclipse.jetty.lifecyleCallbackCollection=org.eclipse.jetty.plus.annotation.LifeCycleCallbackCollection@4909b8da
 |   +> org.eclipse.jetty.server.Executor=qtp1044036744{STARTED,8<=8<=200,i=3,q=0}
 |   +> org.eclipse.jetty.injectionCollection=org.eclipse.jetty.plus.annotation.InjectionCollection@3a03464
 |   +> org.eclipse.jetty.runAsCollection=org.eclipse.jetty.plus.annotation.RunAsCollection@2d3fcdbd
 +- {}
 +- {}
 +- {}
 += org.eclipse.jetty.server.session.HashSessionIdManager@3567135c - STARTED
 |
 +> sun.misc.Launcher$AppClassLoader@45ee12a7
     +- file:/Users/btoal/git/web-tech-stack/target/wts-1-SNAPSHOT.jar
     +- sun.misc.Launcher$ExtClassLoader@6615435c

**Comment by joakime** [comment]
Strange ... your .dumpStdErr() didn't list your Classpath.

You should have the javax.websocket.server implementation jar and its associated dependencies in your classpath for that to work.

(In maven terms ...)

```
<dependency>
    <groupId>org.eclipse.jetty.websocket</groupId>
    <artifactId>javax-websocket-server-impl</artifactId>
    <version>9.3.3.v20150827</version>
</dependency>
```

**Comment by joakime** [comment]
When creating a fatjar with all of the classes ...
you'll need to be careful to merge any existing `META-INF/services/` files.  

The [maven-shade-plugin](https://maven.apache.org/plugins/maven-shade-plugin/) has [Transformers](https://maven.apache.org/plugins/maven-shade-plugin/examples/resource-transformers.html#ServicesResourceTransformer) that can do his sort of merging of `META-INF/services` files for you.

**Comment by toaler** [comment]
Yah I tried adding the dependency you mentioned.  Also META-INF/services doesn't exist in my project setup.

You can try cloning and running my project here:

git clone https://github.com/toaler/web-tech-stack.git
cd web-tech-stack
mvn package; java -jar /Users/btoal/git/web-tech-stack/target/wts-1-SNAPSHOT.jar  2>&1 | tee log.out

The servlets that are specified in web.xml are picked up fine, however the Test.java which uses annotations is not.

**Comment by janbartel** [comment]
Brian,

have a read of this thread:
https://dev.eclipse.org/mhonarc/lists/jetty-users/msg05500.html

IIRC there was also a bug raised in the last year or so that has some
relevant discussion there too - try googling for it.

The problem is that the Test class will be on the equivalent of the
container's classpath, not the webapp's classpath. Thus, as by default we
only scan stuff on the container's classpath that matches a specific
pattern (which by default only matches jsp related jars anyway, see
https://www.eclipse.org/jetty/documentation/current/using-annotations.html
for more info) nothing will be scanned in your case.  You need to find a
pattern that will cause the Test class to be scanned - the pattern is based
on the urls reported by the parent of the webapp's classloader (look at the
dump output for WebAppClassLoader to see the list of parent urls).

regards
Jan

On 9 September 2015 at 04:19, Brian Toal notifications@github.com wrote:

> Yah I tried adding the dependency you mentioned. Also META-INF/services
> doesn't exist in my project setup.
> 
> You can try cloning and running my project here:
> 
> git clone https://github.com/toaler/web-tech-stack.git
> cd web-tech-stack
> mvn package; java -jar
> /Users/btoal/git/web-tech-stack/target/wts-1-SNAPSHOT.jar 2>&1 | tee log.out
> 
> The servlets that are specified in web.xml are picked up fine, however the
> Test.java which uses annotations is not.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jetty-project/embedded-servlet-3.1/issues/5#issuecomment-138655685
> .

## 

Jan Bartel janb@webtide.com
www.webtide.com
_Expert assistance from the creators of Jetty and CometD_

**Comment by toaler** [comment]
Thanks Jan, I was able to get scanning working based on your tip to use ContainerIncludeJarPattern.  One thing I haven't be able to work out is where ContainerIncludeJarPattern class lives.  I can't seem to find that class in my maven project in eclipse.

**Comment by janbartel** [comment]
Brian

> Thanks Jan, I was able to get scanning working based on your tip to use
> ContainerIncludeJarPattern.

Good.

> One thing I haven't be able to work out is where
> ContainerIncludeJarPattern class lives. I can't seem to find that class in
> my maven project in eclipse.

That's beause its not a class. Its a context attribute:
https://www.eclipse.org/jetty/documentation/current/configuring-webapps.html#container-include-jar-pattern

cheers

## Jan

Jan Bartel janb@webtide.com
www.webtide.com
_Expert assistance from the creators of Jetty and CometD_
